[package]
name = "holochain_wasmer_common"
description = "commons for both host and guest"
license = "GPL-3.0-only"
version = "0.0.64"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[dependencies]
holochain_serialized_bytes = { path = "../../../holochain-serialization/crates/holochain_serialized_bytes"}
serde = { version = "1.0.104", features = ["serde_derive"] }
thiserror = "1.0.10"
serde_bytes = "0.11"
