[package]
name = "holochain_wasmer_guest"
description = "wasm guest code"
license = "GPL-3.0-only"
version = "0.0.64"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[workspace]

[lib]
name = "holochain_wasmer_guest"
crate-type = [ "cdylib", "rlib" ]
path = "src/guest.rs"

[dependencies]
holochain_wasmer_common = { version = "=0.0.64", path = "../common" }
holochain_serialized_bytes = { path = "../../../holochain-serialization/crates/holochain_serialized_bytes"}
serde = "=1.0.104"
